#!/bin/sh

JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home

"$JAVA_HOME/bin/java" \
	-cp "$JAVA_HOME/lib/jconsole.jar:$JAVA_HOME/lib/tools.jar:bin:lib/jmxremote_optional.jar:/Users/gerco//development/apache-activemq-5.2.0/activemq-all-5.2.0.jar" \
	-Djmx.remote.protocol.provider.pkgs=nl.gdries.jmsjmx \
	sun.tools.jconsole.JConsole
	
